# Generated by Django 4.1.4 on 2022-12-14 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_option_iscorrect_alter_option_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='content',
            new_name='text',
        ),
    ]
