# Generated by Django 4.1.4 on 2022-12-14 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_rename_content_option_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='text',
            new_name='content',
        ),
    ]
